// CSV Generator Helper for Reports

export const generateSalesReportCSV = (data) => {
  const {
    restaurant,
    period,
    currentStart,
    currentEnd,
    currentMetrics,
    trends,
    revenueData,
    topItems,
  } = data;

  const formatCurrency = (value) => value.toFixed(2);
  const formatDate = (dateStr) => {
    const date = new Date(dateStr);
    return date.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  };
  const formatPeriod = () => {
    const labels = {
      today: "Today",
      yesterday: "Yesterday",
      week: "Last 7 Days",
      month: "Last 30 Days",
      custom: "Custom Range",
    };
    return labels[period] || "Last 7 Days";
  };

  let csv = "";

  // ===== HEADER SECTION =====
  csv += "SALES REPORT\n";
  csv += `Restaurant,${restaurant.name}\n`;
  csv += `Period,${formatPeriod()}\n`;
  csv += `Date Range,${formatDate(currentStart)} - ${formatDate(currentEnd)}\n`;
  csv += `Generated,${new Date().toLocaleString("en-US")}\n`;
  csv += "\n";

  // ===== SUMMARY METRICS SECTION =====
  csv += "SUMMARY METRICS\n";
  csv += "Metric,Value,Trend,Direction\n";
  csv += `Total Revenue,$${formatCurrency(currentMetrics.totalRevenue)},${trends.revenue.value}%,${trends.revenue.direction}\n`;
  csv += `Total Orders,${currentMetrics.totalOrders},${trends.orders.value}%,${trends.orders.direction}\n`;
  csv += `Avg Order Value,$${formatCurrency(currentMetrics.avgOrderValue)},${trends.avgOrderValue.value}%,${trends.avgOrderValue.direction}\n`;
  csv += `Avg Prep Time,${Math.round(currentMetrics.avgPrepTime / 60)} min,${trends.avgPrepTime.value}%,${trends.avgPrepTime.direction}\n`;
  csv += "\n";

  // ===== REVENUE BREAKDOWN SECTION =====
  csv += "REVENUE BREAKDOWN\n";
  csv += "Date,Revenue,Orders,Avg per Order\n";
  revenueData.forEach((item) => {
    const avgOrder = item.orderCount > 0 ? item.revenue / item.orderCount : 0;
    csv += `${formatDate(item.date)},$${formatCurrency(item.revenue)},${item.orderCount},$${formatCurrency(avgOrder)}\n`;
  });
  csv += "\n";

  // ===== TOP SELLING ITEMS SECTION =====
  csv += "TOP SELLING ITEMS\n";
  csv += "Rank,Item Name,Quantity,Revenue\n";
  topItems.forEach((item, index) => {
    csv += `${index + 1},${item.name},${item.totalQuantity},$${formatCurrency(item.totalRevenue)}\n`;
  });
  csv += "\n";

  // ===== FOOTER =====
  csv += `Generated by Smart Restaurant System\n`;

  return csv;
};
